// Code generated by go-swagger; DO NOT EDIT.

package activitypub

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/go-ap/activitypub"
)

// ActivitypubPersonReader is a Reader for the ActivitypubPerson structure.
type ActivitypubPersonReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActivitypubPersonReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewActivitypubPersonOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /activitypub/user-id/{user-id}] activitypubPerson", response, response.Code())
	}
}

// NewActivitypubPersonOK creates a ActivitypubPersonOK with default headers values
func NewActivitypubPersonOK() *ActivitypubPersonOK {
	return &ActivitypubPersonOK{}
}

/*
ActivitypubPersonOK describes a response with status code 200, with default header values.

ActivityPub
*/
type ActivitypubPersonOK struct {
	Payload *models.Person
}

// IsSuccess returns true when this activitypub person o k response has a 2xx status code
func (o *ActivitypubPersonOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this activitypub person o k response has a 3xx status code
func (o *ActivitypubPersonOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this activitypub person o k response has a 4xx status code
func (o *ActivitypubPersonOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this activitypub person o k response has a 5xx status code
func (o *ActivitypubPersonOK) IsServerError() bool {
	return false
}

// IsCode returns true when this activitypub person o k response a status code equal to that given
func (o *ActivitypubPersonOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the activitypub person o k response
func (o *ActivitypubPersonOK) Code() int {
	return 200
}

func (o *ActivitypubPersonOK) Error() string {
	return fmt.Sprintf("[GET /activitypub/user-id/{user-id}][%d] activitypubPersonOK  %+v", 200, o.Payload)
}

func (o *ActivitypubPersonOK) String() string {
	return fmt.Sprintf("[GET /activitypub/user-id/{user-id}][%d] activitypubPersonOK  %+v", 200, o.Payload)
}

func (o *ActivitypubPersonOK) GetPayload() *models.Person {
	return o.Payload
}

func (o *ActivitypubPersonOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Person)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
